class LocalizationMap {
  static Map<String, String> get codesEN => {
    // onboarding
    "skip_lbl" :"Skip",
    "Get_Started_lbl" :"Get Started",
    "Next_lbl":"Next",
    "Discover_Gyms_Near_You":"Discover Gyms Near You",
    "Find_the_best_gyms_with_ratings_photos_directions":"Find the best gyms with ratings, photos & directions",
    "Join_Exciting_Competitions":"Join Exciting Competitions",
    "Challenge_yourself_and_win_real_cash_or_prizes":"Challenge yourself and win real cash or prizes",
    "Track_Your_Wins_Rewards":"Track Your Wins & Rewards",
    "See_winners_claim_prizes_and_stay_motivated":"See winners, claim prizes, and stay motivated",
    // Registration Screen
    "Enter_your_full_name_and_phone_number":"Enter your full name and phone number to create your profile",
    "Full_Name_lbl":"Full Name",
    "Phone_Number_lbl":"Phone Number",
    "Error-lbl":"Error",
    "Please_accept_terms_and_conditions":"Please accept terms and conditions",
    "title_lbl":"title",
    "password_should_contain_at_least_eight_character": "Password should contain at least 8 character",
    "password_should_be_alphanumeric": "Password should be alphanumeric",
    "password_should_have_capital_alphabet": "Password should have a capital alphabet",
    "password_should_1_special_character": "Password should have 1 special character",
    "email_is_required": "Please enter your email address",
    "enter_a_valid_Email": "Invalid email address",
    "please_enter_your_password": "Please enter your password",
    "please_re_enter_your_password": "Please re-enter your password",
    "password_does_not_match": "Password does mot match",
    "please_enter_your_first_name": "Please enter your name",
    "invalid_name": "Invalid name",
    "please_enter_your_last_name": "Please enter your last name",
    "gallery": "Gallery",
    "camera": "Camera",
    "remove_profile_image": "Remove Profile Image",
    "view_profile_image": "View Profile Image",
    "press_again_to_exit": "Press again to exit.",
    "no_internet_connection": "No Internet Connection",
    "oops": "Oops",
    "please_grant_required_permissions": "Please grant the required permissions",
    "open_settings": "Open Settings",
    "server_error":"Server Error",
    "back":"Back",
    "please_enter_otp":"Please enter OTP",
    "please_enter_your_otp":"Please enter your OTP",
    "invalid_otp":"Invalid OTP",
    "did_not_get_code":"Did not get code",
    "resend_otp":"Resend OTP",
    "verify":"Verify",
    "continue_button":"Continue",
    "register":"Register",
    "already_have_account":"Already have an account? Sign in",
    "forgot_password_help":"Forgot Password?",
    "otp_sent_message":"We'll send an OTP to your number",
    "name_required":"Name is required",
    "name_min_length":"Name must be at least 2 characters",
    "name_max_length":"Name must not exceed 60 characters",
    "name_invalid_characters":"Name can only contain letters, hyphen, and apostrophe",
    "phone_required":"Phone number is required",
    "phone_invalid_length":"Phone number must be between 7 and 15 digits",
    "phone_numeric_only":"Phone number must contain only numbers",
    "country_code_required":"Country code is required",
    "otp_verification_success":"OTP verified successfully",
    "otp_verification_failed":"Invalid OTP. Please try again",
    "registration_success":"Registration successful",
    "didnt_receive_code":"Didn't receive code?",
    "ok":"OK",
    "welcome_text":"Welcome Back 👋",
    "login_to_continue":"Login to continue",
    "email_address":"Email Address",
    "password":"Password",
    "enter_password":"Enter password",
    "forgot_password":"Forgot Password?",
    "login":"Login",
    "don't_have_account":"Don't have an account? ",
    "sign_up":"Sign Up",
    // Login SignUp
    "welcome_back": "Welcome back!",
    "we_missed_you": "We missed you !",
    "enter_email": "Enter your email",
      "or_login_with": "Or Login with",
    "hello": "Hello!",
    "register_to_get_started": "Register to get started",
    "full_name": "Full Name",
    "username": "Username",
    "email": "Email",
    "confirm_password": "Confirm password",
    "confirm_password_cap": "Confirm Password",
    "agree_to": "I Agree to the ",
    "verify_lbl":"verify",
    "terms_and_condition": "Terms of Service ",
    "and": "and ",
    "privacy_policy": "Privacy Policy",
    "create": "Create",
    "already_have_account_login": "Already have an account? Login",
    "otp_verification": "OTP Verification",
    "enter_verification_code":
    "Enter the verification code we just sent you via text message on your phone number.",
    "resend_code": "Didn't receive the code?",
    "resend": "Resend",
    "account_created": "Account Created",
    "account_created_success": "Your account has been created successfully.",
    "home_lbl":"home",
    // Notification Screen
    "Notification_title":"Notifications",
    "Competition_Updates":"Competition Updates",
    "Announcements_lbl":"Announcements",
    "Winner_Notifications":"Winner Notifications",
    "Appearance_lbl":"Appearance",
    "Dark_Mode":"Dark Mode",
    "Account_Setting":"Account Setting",
    "Delete_Account":"Account Setting",
    // Profile Screen
    "my_profile":"My Profile",
    "Edit_Name":"Edit Name",
    "Account_lbl":"Account",
    "Saved_Gyms":"Saved Gyms",
    "My_Prizes":"My Prizes",
    "Logout_lbl":"Logout",
    // Setting Screen
    "Settings-lbl":"Settings",
    "Enter_your_name":"Enter your name",
    "Cancel_lbl":"Cancel",
    "Save_lbl":"Save",
    "logout_lbl":"Logout",
    "want_to_logout_from_your_account?":"Are you sure you want to logout from your account?",
    // Help & Support Screen
    "help_and_support": "Help & Support",
    "faqs": "FAQs",
    "support": "Support",
    "legal": "Legal",
    "contact_support": "Contact Support",
    "report_an_issue": "Report an Issue",
    "terms_and_conditions": "Terms & Conditions",
    "app_version": "App Version 1.0.0",
    "support_chat": "Support Chat",
    "support_online": "Online",
    "support_greeting_message": "Hello! How can we help you today?",
    "type_a_message": "Type a message...",
    "faq1_question": "How can I find nearby gyms?",
    "faq1_answer": "Go to the Gym Locator section and enable location access. The app will automatically show gyms near you along with distance and ratings.",
    "faq2_question": "How do I view details about a gym?",
    "faq2_answer": "Tap on any gym in the list to open its detail page. You can see photos, address, opening hours, ratings, and reviews.",
    "faq3_question": "Can I save a gym for later?",
    "faq3_answer": "Yes. Tap the heart icon on any gym detail page to save it to your favorites. You can access all saved gyms from your Profile section.",
    // Terms & Conditions Screen
    "terms_conditions_title": "Terms & Conditions",
    "tc_1_intro": "1. Introduction",
    "tc_1_text": "These Terms & Conditions govern your use of the uniofit mobile application, including competitions, gym discovery, user profile features, and prize claims.",
    "tc_2_eligibility": "2. Eligibility",
    "tc_2_1": "You must provide accurate full name and phone number.",
    "tc_2_2": "One account per user is allowed.",
    "tc_2_3": "You must be 18 years or older to participate in competitions.",
    "tc_3_competition": "3. Competition Participation",
    "tc_3_1": "Only active competitions shown in the app can be joined.",
    "tc_3_2": "A user may enroll once per competition.",
    "tc_3_3": "Online competitions may require a photo submission.",
    "tc_3_4": "Offline competitions require attending the event at the specified venue.",
    "tc_3_5": "Enrollment cannot be reversed after submission.",
    "tc_4_winner": "4. Winner Selection",
    "tc_4_1": "Winners are selected and announced solely by the admin.",
    "tc_4_2": "uniofit reserves the right to verify user identity before confirming a winner.",
    "tc_4_3": "All winner decisions made by the admin are final.",
    "tc_5_prize": "5. Prize Claims",
    "tc_5_1": "Cash prize winners must submit accurate bank details.",
    "tc_5_2": "Physical prize winners must provide valid shipping information.",
    "tc_5_3": "Processing time may vary depending on verification and admin approval.",
    "tc_5_4": "Incorrect or incomplete information may delay or cancel the claim.",
    "tc_6_gym": "6. Gym Locator",
    "tc_6_1": "Gym data is sourced from Google Places and may not always be 100% accurate.",
    "tc_6_2": "uniofit is not responsible for incorrect gym details, timings, or availability.",
    "tc_6_3": "Saved gyms are stored for convenience only.",
    "tc_7_account": "7. Account Responsibilities",
    "tc_7_1": "You must keep your login information secure.",
    "tc_7_2": "uniofit may block accounts involved in suspicious or fraudulent activity.",
    "tc_7_3": "Device fingerprinting may be used to prevent multiple fake accounts.",
    "tc_8_notifications": "8. Notifications",
    "tc_8_1": "By using the app, you agree to receive competition updates, announcements, and winner notifications.",
    "tc_8_2": "Notifications can be turned off in the Settings section.",
    "tc_9_data": "9. Data & Privacy",
    "tc_9_1": "Your submitted data is stored securely and used only for app functionality.",
    "tc_9_2": "Bank details and shipping information are encrypted.",
    "tc_9_3": "We do not sell or share your personal data with third parties.",
    "tc_10_prohibited": "10. Prohibited Activities",
    "tc_10_1": "Creating multiple accounts.",
    "tc_10_2": "Submitting false information or fraudulent entries.",
    "tc_10_3": "Using the app for unlawful activities.",
    "tc_10_4": "Abusing competitions or attempting to manipulate results.",
    "tc_11_liability": "11. Liability Disclaimer",
    "tc_11_1": "uniofit is not responsible for physical injuries during offline competitions.",
    "tc_11_2": "We do not guarantee gym availability, service quality, or pricing.",
    "tc_11_3": "The app is provided on an 'as-is' basis without warranties.",
    "tc_12_admin": "12. Admin Rights",
    "tc_12_1": "The admin may update competitions, rules, or app features at any time.",
    "tc_12_2": "These Terms may be updated without prior notice.",
    "tc_12_3": "Continued use of the app means you accept updated Terms.",
    "last_updated_march_2026": "Last Updated: March 2026",
    // Privacy Policy Screen
    "privacy_policy_title": "Privacy Policy",
    "pp_1_intro": "1. Introduction",
    "pp_1_text": "This Privacy Policy explains how uniofit collects, uses, and protects your information when you use the application including competitions, gym discovery, and prize claims.",
    "pp_2_collect": "2. Information We Collect",
    "pp_2_1": "Full name and phone number during registration.",
    "pp_2_2": "Competition enrollment and participation data.",
    "pp_2_3": "Photos or text submissions for online competitions.",
    "pp_2_4": "Device information used for security and notifications.",
    "pp_2_5": "Location information for gym discovery features.",
    "pp_3_use": "3. How We Use Your Information",
    "pp_3_1": "To create and manage your user account.",
    "pp_3_2": "To allow participation in competitions.",
    "pp_3_3": "To verify winners and process prize claims.",
    "pp_3_4": "To improve application performance and user experience.",
    "pp_3_5": "To send important updates, announcements, and notifications.",
    "pp_4_competition": "4. Competition Participation Data",
    "pp_4_1": "Competition enrollment records are stored for fairness and verification.",
    "pp_4_2": "Entries submitted in competitions may be reviewed by administrators.",
    "pp_4_3": "Winner names and prize details may be publicly displayed in the app.",
    "pp_5_prize": "5. Prize Claim Information",
    "pp_5_1": "Cash prize winners may provide bank account details.",
    "pp_5_2": "Physical prize winners may submit shipping address information.",
    "pp_5_3": "Sensitive information such as banking details is encrypted and stored securely.",
    "pp_6_gym": "6. Gym Locator",
    "pp_6_1": "The gym locator uses Google Places services to display nearby gyms.",
    "pp_6_2": "Location permission may be required to show gyms near your location.",
    "pp_6_3": "Saved gyms are stored for user convenience.",
    "pp_7_notifications": "7. Notifications",
    "pp_7_1": "The application may send notifications about competitions, winners, and announcements.",
    "pp_7_2": "Users can disable notifications from the settings screen.",
    "pp_7_3": "Device tokens may be stored to deliver push notifications.",
    "pp_8_security": "8. Data Security",
    "pp_8_1": "We take appropriate measures to protect user information.",
    "pp_8_2": "Sensitive data such as banking details is encrypted.",
    "pp_8_3": "Only authorized administrators have access to sensitive data.",
    "pp_9_sharing": "9. Data Sharing",
    "pp_9_1": "We do not sell or rent your personal information.",
    "pp_9_2": "Limited data may be processed by third-party services such as Google Maps and Firebase.",
    "pp_9_3": "Information may be disclosed if required by law.",
    "pp_10_rights": "10. User Rights",
    "pp_10_1": "Users can update their profile information.",
    "pp_10_2": "Users may request account deletion through support.",
    "pp_10_3": "Users can manage notification preferences within the app.",
    "pp_11_changes": "11. Changes to Privacy Policy",
    "pp_11_1": "This privacy policy may be updated from time to time.",
    "pp_11_2": "Updated policies will be reflected inside the application.",
    "pp_11_3": "Continued use of the application indicates acceptance of the updated policy.",
    "pp_12_contact": "12. Contact",
    "pp_12_1": "For any privacy related concerns please contact the application support team.",
    // Help support Screen (legacy / forgot password)
    "back_to_login": "Back to Login",
    "forgot_password_subtitle":
    "Don't worry! It occurs. Please enter the email address linked with your account.",
    "send_code": "Send Code",
    "remember_password": "Remember Password?",
    "create_new_password": "Create new password",
    "create_password_subtitle":
    "Your new password must be unique from those previously used.",
    "new_password": "New Password",
    "reset_password": "Reset Password",
    "change_password": "Change Password",
    "password_changed": "Password Changed!",
    "password_changed_success": "Your password has been changed successfully.",
    "no_profiles_available": "No profiles available",
    // App metadata
    "app_name": "Unio Fit",
    
    // Navigation & Screens
    "error": "Error",
    "dashboard": "Dashboard",
    "registration": "Registration",
    "registration_screen": "Registration Screen",
    
    // Splash Screen
    "splash_tagline": "Your Fitness Journey Starts Here",
    
    // Common
    "loading": "Loading...",
    "placeholder_button": "Placeholder Button",
    "clean_architecture_ready": "Clean Architecture + Riverpod Ready",
    "pre_filled_phone": "Pre-filled phone:",
    "this_screen_will_be_implemented": "This screen will be implemented in future user stories.",
    "dashboard_screen_text": "Dashboard",
    "route_not_found": "Route not found:",
    "home":"Home",
    
    // Dashboard
    "quick_stats": "Quick Stats",
    "recent_activities": "Recent Activities",
    "view_all": "View All",
    "quick_actions": "Quick Actions",
    "total_workouts": "Total Workouts",
    "active_plans": "Active Plans",
    "calories_burned": "Calories Burned",
    "streak_days": "Streak Days",
    "start_workout": "Start Workout",
    "view_programs": "View Programs",
    "track_progress": "Track Progress",
    
    // Competition
    "active_competition": "Active Competition",
    "upcoming_competition": "Upcoming Competition",
    "upcoming": "Upcoming",
    "participants": "Participants",
    "prize": "Prize",
    "join_competition": "Join Competition",
    "no_competitions_available": "No Competitions Available",
    "no_competitions_description": "Check back later for new competitions and challenges!",
    "starts_in": "Starts in",
    "empty_state": "Empty State",
    
    // Competition Announcement
    "announcement": "Announcement",
    "announcements": "Announcements",
    "new_competitions_launching_soon": "New competitions launching soon.",
    "stay_tuned": "Stay tuned!",
    
    // Dashboard Stats
    "total_winners": "Total Winners",
    "total_cash_distributed": "Total Cash Distributed",
    
    // Competition
    "enroll_now": "Enroll Now",
    
    // Empty Dashboard State
    "no_competition_right_now": "No competition right now — but keep checking!",
    "we_are_planning_something_big": "We're planning something big.",
    "browse_gyms_around_you": "In the meantime, browse gyms around you.",
    "find_gyms": "Find Gyms",
    
    // Search placeholders
    "search_competitions": "Search competitions",
    "search_upcoming_competitions": "Search upcoming competitions",
    "search_announcements": "Search announcements",
    
    // Competition Details
    "competition_details": "Competition Details",
    "online": "ONLINE",
    "offline": "OFFLINE",
    "active": "ACTIVE",
    "enrollment_closed": "ENROLLMENT CLOSED",
    "judging": "JUDGING",
    "announced": "ANNOUNCED",
    "start_date": "Start Date",
    "end_date": "End Date",
    "participants_count": "Participants",
    "prize_amount": "Prize",
    "description": "Description",
    "rules_and_requirements": "Rules & Requirements",
    "prize_information": "Prize Information",
    "grand_prize": "Grand Prize",
    "runner_up": "Runner Up",
    "enroll_confirmation": "Are you sure you want to enroll in this competition?",
    "enrollment_success": "You are successfully enrolled!",
    "submit_entry": "Submit Entry",
    "upload_photo": "Upload Transformation Photo",
    "add_description": "Add Description",
    "submit_entry_button": "Submit Entry",
    "submission_success": "Your entry has been submitted successfully!",
    "gym_check_in": "Gym Check-In",
    "selected_gym": "Selected Gym",
    "check_in_at_gym": "Check In at Gym",
    "check_in_confirmation": "Confirm check-in at this gym?",
    "check_in_success": "Check-in successful!",
    "enrolled": "Enrolled",
    "submission_received": "Submission Received",
    "under_judging": "Under Judging",
    "winner_announced": "Winner Announced",
    "submissions_under_review": "Submissions are currently under review.",
    "winner_announced_title": "Winner Announced",
    "winner": "Winner",
    "congratulations": "Congratulations!",
  };

  static String getValues(String key) {
    return codesEN[key] ?? "";

  }
}

extension Localize on String {
  String L() {
    return LocalizationMap.getValues(this);
  }
}
