class LocalizationMap {
  static Map<String, String> get codesEN => {
    "password_should_contain_at_least_eight_character": "Password should contain at least 8 character",
    "password_should_be_alphanumeric": "Password should be alphanumeric",
    "password_should_have_capital_alphabet": "Password should have a capital alphabet",
    "password_should_1_special_character": "Password should have 1 special character",
    "email_is_required": "Please enter your email address",
    "enter_a_valid_Email": "Invalid email address",
    "please_enter_your_password": "Please enter your password",
    "please_re_enter_your_password": "Please re-enter your password",
    "password_does_not_match": "Password does mot match",
    "please_enter_your_first_name": "Please enter your name",
    "invalid_name": "Invalid name",
    "please_enter_your_last_name": "Please enter your last name",
    "gallery": "Gallery",
    "camera": "Camera",
    "remove_profile_image": "Remove Profile Image",
    "view_profile_image": "View Profile Image",
    "press_again_to_exit": "Press again to exit.",
    "no_internet_connection": "No Internet Connection",
    "oops": "Oops",
    "please_grant_required_permissions": "Please grant the required permissions",
    "open_settings": "Open Settings",
    "server_error":"Server Error",
    "back":"Back",
    "please_enter_otp":"Please enter OTP",
    "please_enter_your_otp":"Please enter your OTP",
    "invalid_otp":"Invalid OTP",
    "did_not_get_code":"Did not get code",
    "resend_otp":"Resend OTP",
    "verify":"Verify",
    "continue_button":"Continue",
    "register":"Register",
    "already_have_account":"Already have an account? Sign in",
    "forgot_password_help":"Forgot Password?",
    "otp_sent_message":"We'll send an OTP to your number",
    "name_required":"Name is required",
    "name_min_length":"Name must be at least 2 characters",
    "name_max_length":"Name must not exceed 60 characters",
    "name_invalid_characters":"Name can only contain letters, hyphen, and apostrophe",
    "phone_required":"Phone number is required",
    "phone_invalid_length":"Phone number must be between 7 and 15 digits",
    "phone_numeric_only":"Phone number must contain only numbers",
    "country_code_required":"Country code is required",
    "otp_verification_success":"OTP verified successfully",
    "otp_verification_failed":"Invalid OTP. Please try again",
    "registration_success":"Registration successful",
    "didnt_receive_code":"Didn't receive code?",
    "ok":"OK",
    "welcome_text":"Welcome Back 👋",
    "login_to_continue":"Login to continue",
    "email_address":"Email Address",
    "password":"Password",
    "enter_password":"Enter password",
    "forgot_password":"Forgot Password?",
    "login":"Login",
    "don't_have_account":"Don't have an account? ",
    "sign_up":"Sign Up",
    // Login SignUp
    "welcome_back": "Welcome back!",
    "we_missed_you": "We missed you !",
    "enter_email": "Enter your email",
      "or_login_with": "Or Login with",
    "hello": "Hello!",
    "register_to_get_started": "Register to get started",
    "full_name": "Full Name",
    "username": "Username",
    "email": "Email",
    "confirm_password": "Confirm password",
    "confirm_password_cap": "Confirm Password",
    "agree_to": "I Agree to the ",
    "terms_and_condition": "Terms of Service ",
    "and": "and ",
    "privacy_policy": "Privacy Policy",
    "create": "Create",
    "already_have_account_login": "Already have an account? Login",
    "otp_verification": "OTP Verification",
    "enter_verification_code":
    "Enter the verification code we just sent you via text message on your phone number.",
    "resend_code": "Didn't receive the code?",
    "resend": "Resend",
    "account_created": "Account Created",
    "account_created_success": "Your account has been created successfully.",
    "back_to_login": "Back to Login",
    "forgot_password_subtitle":
    "Don't worry! It occurs. Please enter the email address linked with your account.",
    "send_code": "Send Code",
    "remember_password": "Remember Password?",
    "create_new_password": "Create new password",
    "create_password_subtitle":
    "Your new password must be unique from those previously used.",
    "new_password": "New Password",
    "reset_password": "Reset Password",
    "change_password": "Change Password",
    "password_changed": "Password Changed!",
    "password_changed_success": "Your password has been changed successfully.",
    "no_profiles_available": "No profiles available",
    // App metadata
    "app_name": "Unio Fit",
    
    // Navigation & Screens
    "error": "Error",
    "dashboard": "Dashboard",
    "registration": "Registration",
    "registration_screen": "Registration Screen",
    
    // Splash Screen
    "splash_tagline": "Your Fitness Journey Starts Here",
    
    // Common
    "loading": "Loading...",
    "placeholder_button": "Placeholder Button",
    "clean_architecture_ready": "Clean Architecture + Riverpod Ready",
    "pre_filled_phone": "Pre-filled phone:",
    "this_screen_will_be_implemented": "This screen will be implemented in future user stories.",
    "dashboard_screen_text": "Dashboard",
    "route_not_found": "Route not found:",
    "home":"Home",
    
    // Dashboard
    "quick_stats": "Quick Stats",
    "recent_activities": "Recent Activities",
    "view_all": "View All",
    "quick_actions": "Quick Actions",
    "total_workouts": "Total Workouts",
    "active_plans": "Active Plans",
    "calories_burned": "Calories Burned",
    "streak_days": "Streak Days",
    "start_workout": "Start Workout",
    "view_programs": "View Programs",
    "track_progress": "Track Progress",
    
    // Competition
    "active_competition": "Active Competition",
    "upcoming_competition": "Upcoming Competition",
    "upcoming": "Upcoming",
    "participants": "Participants",
    "prize": "Prize",
    "join_competition": "Join Competition",
    "no_competitions_available": "No Competitions Available",
    "no_competitions_description": "Check back later for new competitions and challenges!",
    "starts_in": "Starts in",
    "empty_state": "Empty State",
    
    // Competition Announcement
    "announcement": "Announcement",
    "announcements": "Announcements",
    "new_competitions_launching_soon": "New competitions launching soon.",
    "stay_tuned": "Stay tuned!",
    
    // Dashboard Stats
    "total_winners": "Total Winners",
    "total_cash_distributed": "Total Cash Distributed",
    
    // Competition
    "enroll_now": "Enroll Now",
    
    // Empty Dashboard State
    "no_competition_right_now": "No competition right now — but keep checking!",
    "we_are_planning_something_big": "We're planning something big.",
    "browse_gyms_around_you": "In the meantime, browse gyms around you.",
    "find_gyms": "Find Gyms",
    
    // Search placeholders
    "search_competitions": "Search competitions",
    "search_upcoming_competitions": "Search upcoming competitions",
    "search_announcements": "Search announcements",
    
    // Competition Details
    "competition_details": "Competition Details",
    "online": "ONLINE",
    "offline": "OFFLINE",
    "active": "ACTIVE",
    "enrollment_closed": "ENROLLMENT CLOSED",
    "judging": "JUDGING",
    "announced": "ANNOUNCED",
    "start_date": "Start Date",
    "end_date": "End Date",
    "participants_count": "Participants",
    "prize_amount": "Prize",
    "description": "Description",
    "rules_and_requirements": "Rules & Requirements",
    "prize_information": "Prize Information",
    "grand_prize": "Grand Prize",
    "runner_up": "Runner Up",
    "enroll_confirmation": "Are you sure you want to enroll in this competition?",
    "enrollment_success": "You are successfully enrolled!",
    "submit_entry": "Submit Entry",
    "upload_photo": "Upload Transformation Media",
    "add_description": "Add Description",
    "submit_entry_button": "Submit Entry",
    "submission_success": "Your entry has been submitted successfully!",
    "gym_check_in": "Gym Check-In",
    "selected_gym": "Selected Gym",
    "check_in_at_gym": "Check In at Gym",
    "check_in_confirmation": "Confirm check-in at this gym?",
    "check_in_success": "Check-in successful!",
    "enrolled": "Enrolled",
    "submission_received": "Submission Received",
    "under_judging": "Under Judging",
    "winner_announced": "Winner Announced",
    "submissions_under_review": "Submissions are currently under review.",
    "winner_announced_title": "Winner Announced",
    "winner": "Winner",
    "congratulations": "Congratulations!",
    
    // Media Picker
    "choose_media_source": "Choose Media Source",
    "camera": "Camera",
    "gallery": "Gallery",
    "select_media_type": "Select Media Type",
    "photo": "Photo",
    "video": "Video",
    
    // Permissions
    "camera_permission_required": "Camera permission is required to take photos or videos.",
    "storage_permission_required": "Storage permission is required to access your gallery.",
    "permission_denied": "Permission Denied",
    "permission_denied_message": "Please grant the required permission in your device settings to continue.",
    "open_settings": "Open Settings",
    "cancel": "Cancel",
    
    // Video Trimmer
    "video_too_long": "Video must be less than 30 seconds. Please trim your video.",
    "trim_video": "Trim Video",
    "trim": "Trim",
    "save": "Save",
    "failed_to_load_video": "Failed to load video",
    "uploading_entry": "Uploading Entry...",
    "entry_submitted_mock": "Entry submitted (mock)",
    "video_duration_exceeded": "Video duration exceeded",
    "select_video_to_trim": "Select video to trim",
    "max_duration": "Maximum duration: 60 seconds",
  };

  static String getValues(String key) {
    return codesEN[key] ?? "";

  }
}

extension Localize on String {
  String L() {
    return LocalizationMap.getValues(this);
  }
}
